version: "3.6"
services:
  shinyproxy:
    #build:
    #  dockerfile: Dockerfile.shinyproxy
    #depends_on:
    #  - nginx
    #  - influxdb
    image: roche/shinyproxy
    container_name: roche_shinyproxy
    restart: on-failure
    networks:
      - tki-net
    volumes:
      - ./shinyproxy/application.yml:/opt/shinyproxy/application.yml
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8888:8080
networks:
  tki-net:
    name: tki-net
