version: "3.6"
services:
  shinyproxy:
    #build:
    #  dockerfile: Dockerfile.shinyproxy
    #depends_on:
    #  - nginx
    #  - influxdb
    image: 2x2contingency_table/shinyproxy
    container_name: 2x2contingency_table_proxy
    restart: on-failure
    networks:
      - biostat-net
    volumes:
      - ./shinyproxy/application.yml:/opt/shinyproxy/application.yml
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8888:8080
networks:
  biostat-net:
    name: biostat-net
