proxy:
  title: "Roche Interview : Michael King"
  hide-navbar: false
  landing-page: /
  heartbeat-rate: 10000
  heartbeat-timeout: 600000
  port: 8080
  docker:
    internal-networking: true
  specs:
  - id: shiny_app
    display-name: Test Method Evaluator
    description: Compare a new test with a reference standard.
    container-cmd: ["bash", "/usr/bin/shiny-server.sh"]
    container-image: roche/shiny_app
    container-network: tki-net
    container-env:
      user: "shiny"
      environment:
        - APPLICATION_LOGS_TO_STDOUT=false

logging:
  file:
    shinyproxy.log
